spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: testdb
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa.hibernate.ddl-auto: none

service2-topic: topic2
service2-group-id: group-id2

logging:
  level.root: error
  level:
    org.apache.kafka: error
    org.springframework.kafka: error
    org.apache.kafka.clients.consumer.internals: error
    #    org.springframework.orm.jpa.JpaTransactionManager: trace
    #    org.springframework.kafka.transaction: trace
    #    org.springframework.kafka.core.DefaultKafkaProducerFactory: trace
    com.dragomir.fsm: debug
#    org.springframework.jdbc.core: TRACE

server:
  port: 8081